### PR TITLE
feat: Add TIL on debuggers

### PR DESCRIPTION
**Pull request by TJBANEY**
## 📚 Description
Debugger TIL slides from a while back

### CODE REVIEW

**Review by aaronprice00 — APPROVED** [review]

**Review by rlankfo — APPROVED** [review]
Approved but just as an FYI git is not meant for tracking binary files, and usually recommend not checking binary files into git. Would these slides be more appropriately tracked in Google Drive somewhere?

**Comment by cwhittl** [comment]
I think they are crap... And It looks like 1 of 2 checks agree with me.

**Comment by addamh** [comment]
lol wtf @cwhittl

**Comment by TJBANEY** [comment]
> Approved but just as an FYI git is not meant for tracking binary files, and usually recommend not checking binary files into git. Would these slides be more appropriately tracked in Google Drive somewhere?

I see, yeah no worries. I will upload them the companies Google Drive. Thanks for the tip @rlankfo 🎸

**Comment by TJBANEY** [comment]
> I think they are crap... And It looks like 1 of 2 checks agree with me.

Who do you think you are .... _squints eyes_ @cwhittl

**Comment by TJBANEY** [comment]
I'll close this PR out and update the readme with a link to the Google Drive 👍

**Pull request closed without merging**
